"""add meeting_type column

Revision ID: 8ecfb5449507
Revises: b1f1e4eca86a
Create Date: 2026-07-27 11:55:08.356116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecfb5449507'
down_revision: Union[str, Sequence[str], None] = 'b1f1e4eca86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_type', sa.String(length=10), nullable=True))
    op.alter_column('meetings', 'building',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('meetings', 'room',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'room',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('meetings', 'building',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('meetings', 'meeting_type')
    # ### end Alembic commands ###
