"""create courses, sections, meetings tables

Revision ID: b1f1e4eca86a
Revises: 
Create Date: 2026-07-23 16:53:41.160042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f1e4eca86a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('courseNumber', sa.String(length=30), nullable=False),
    sa.Column('courseTitle', sa.String(length=500), nullable=False),
    sa.Column('subjectCourse', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subjectCourse')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(length=10), nullable=False),
    sa.Column('sequenceNumber', sa.String(length=10), nullable=False),
    sa.Column('scheduleTypeDescription', sa.String(length=500), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('link_group', sa.String(length=50), nullable=False),
    sa.Column('maximumEnrollment', sa.Integer(), nullable=False),
    sa.Column('enrollment', sa.Integer(), nullable=False),
    sa.Column('seatsAvailable', sa.Integer(), nullable=False),
    sa.Column('instructor', sa.String(length=200), nullable=True),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crn')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('building', sa.String(length=200), nullable=False),
    sa.Column('room', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    op.drop_table('sections')
    op.drop_table('courses')
    # ### end Alembic commands ###
