"""add optional to link_type and link_group column

Revision ID: f25c6af0bdc0
Revises: 8ecfb5449507
Create Date: 2026-07-28 11:53:03.946871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25c6af0bdc0'
down_revision: Union[str, Sequence[str], None] = '8ecfb5449507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'link_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sections', 'link_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'link_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sections', 'link_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
